services:

  php_sushi:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php-sushi
    working_dir: /var/html/sushi/
    restart: unless-stopped
    networks:
      - custom-network
    volumes:
      - ./:/var/html/sushi/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    expose:
      - 9000

  nginxserv:
    image: nginx:latest
    container_name: nginx-serv
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./docker/conf.d/:/etc/nginx/conf.d/
      - ./:/var/html/sushi
    networks:
      custom-network:
        aliases:
          - sushi.ua

  mariadb_s:
    image: mariadb:10.5
    container_name: mariadb-s
    restart: always
    networks:
      - custom-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: nopass
      TZ: Europe/Kyiv
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

networks:
  custom-network:
    driver: bridge